<?php

namespace Tiempo\AdminBundle\Repository;

/**
 * pinesMapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pinesMapaRepository extends \Doctrine\ORM\EntityRepository
{
}
